# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
groups:
  angular:
    patterns:
      - "@angular*"
    update-types:
      - "minor"
      - "patch"
  angular-major:
    patterns:
      - "@angular*"
    update-types:
      - "major"
  fortawesome:
    patterns:
      - "@fortawesome*"
  types:
    patterns:
      - "@types/*"
  typescript-eslint:
    patterns:
      - "@typescript-eslint/*"
  eslint:
    patterns:
      - "eslint*"
  karma:
    patterns:
      - "karma*"
