name: Setup
description: Checks out the repository and installs tooling
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
      with:
        node-version-file: '.node-version'
        cache: 'yarn'
    - name: Install dependencies
      # Actually the "--immutable" is enabled by default on CI envs
      # setup-node action uses "--frozen-lockfile" but that is backwards comp and will be removed
      # https://github.com/actions/setup-node/blob/5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d/docs/advanced-usage.md#caching-packages-data
      shell: bash
      run: yarn install --immutable
