name: Setup
description: Checks out the repository and installs tooling
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - name: Setup Node.js
      uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5
      with:
        cache: 'pnpm'
        node-version-file: '.node-version'
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
