name: Setup
description: Checks out the repository and installs tooling
runs:
  using: 'composite'
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@a3252b78c470c02df07e9d59298aecedc3ccdd6d # v3.0.0
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
      with:
        cache: 'pnpm'
        node-version-file: '.node-version'
    # Why this? https://github.com/npm/cli/issues/7279
    # Why this way? https://github.com/actions/setup-node/issues/213
    - name: Install latest npm
      shell: bash
      run: |
        npm install -g npm@latest &&
        npm --version &&
        npm list -g --depth 0
    - name: Install dependencies
      shell: bash
      run: cd .ci && make install
