ci:
  collect:
    staticDistDir: dist/@davidlj95/website/browser
    url:
      - 'http://localhost/resume/'
  assert:
    preset: 'lighthouse:no-pwa'
    assertions:
      # 👇 Just the profile picture when adding this
      image-delivery-insight: warn
      # 👇 Difficult to avoid using Angular
      network-dependency-tree-insight: warn
  upload:
    target: temporary-public-storage
