ci:
  collect:
    staticDistDir: dist/@davidlj95/website/browser
    url:
      - 'http://localhost/resume/'
  assert:
    preset: 'lighthouse:no-pwa'
    assertions:
      bf-cache: warn
      csp-xss: warn
      uses-responsive-images: warn
  upload:
    target: temporary-public-storage
