ci:
  collect:
    staticDistDir: dist/@davidlj95/website/browser
    url:
      - 'http://localhost/resume/'
  assert:
    preset: 'lighthouse:no-pwa'
    assertions:
      # 👇 Angular omits them when bundle size >500kb
      valid-source-maps: warn
      bf-cache: warn
      csp-xss: warn
      unused-javascript: warn
      uses-responsive-images: warn
  upload:
    target: temporary-public-storage
