# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: David LJ aka davidlj95
email: mail@davidlj95.com
description: /dev/random software engineer, geeky guy. Connecting technology & RealLife™. Get to know me better here
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en

# jekyll-seo-tag configurations
# https://github.com/jekyll/jekyll-seo-tag/blob/v2.8.0/docs/usage.md
# Also uses title & description
tagline: A random software engineer, geeky guy
author:
  name: &username
    davidlj95
  url: https://davidlj95.com/
twitter:
  card: summary
  username: *username
  url: &twitter_url
    https://twitter.com/davidlj95
github:
  username: *username
  url: &github_url
    https://github.com/davidlj95
facebook:
  admins: *username
  url: &facebook_url
    https://www.facebook.com/davidlj95
instagram:
  username: *username
  url: &instagram_url
    https://www.instagram.com/davidlj95
linkedin:
  username: *username
  url: &linkedin_url
    https://www.linkedin.com/in/davidlj95
keybase:
  username: *username
  url: &keybase_url
    https://keybase.io/davidlj95
stackoverflow:
  username: *username
  url: &stackoverflow_url
    https://stackoverflow.com/users/3263250/davidlj95

social:
  name: David LJ
  links:
    - *twitter_url
    - *instagram_url
    - *facebook_url
    - *linkedin_url
    - *github_url
    - *keybase_url
    - *stackoverflow_url

webmaster_verifications:
  facebook: 1299426610587748

# Build settings
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
include: [".well-known"]
