coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%
comment:
  hide_project_coverage: false

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
