export const CUSTOM_DISPLAY_NAME_ENTRIES: readonly [string, string][] = [
  ['microsoftword', 'Microsoft Word'],
  ['rspec', 'RSpec'],
  ['zenqms', 'ZenQMS'],
  ['karmarunner', 'Karma Runner'],
  ['http', 'HTTP'],
  ['httprest', 'RESTful'],
  ['googleworkspace', 'Google Workspace'],
  ['oauth2', 'OAuth 2.0'],
  ['junit', 'JUnit'],
  ['jsonld', 'JSON LD'],
  ['blockcerts', 'Blockcerts'],
  ['gitlabcicd', 'GitLab CI/CD'],
  ['gitlabpages', 'GitLab Pages'],
  ['webcomponents', 'Web Components'],
  ['python-unittest', "Python's `unittest`"],
  ['pyqt', 'PyQt'],
  ['java', 'Java'],
  ['html', 'HTML'],
  ['css', 'CSS'],
  // 👇 https://github.com/simple-icons/simple-icons/issues/11236
  ['visualstudiocode', 'Visual Studio Code'],
]
