export const CUSTOM_DISPLAY_NAME_ENTRIES: ReadonlyArray<[string, string]> = [
  ['rspec', 'RSpec'],
  ['redsys', 'Redsys'],
  ['rubymine', 'RubyMine'],
  ['zenqms', 'ZenQMS'],
  ['karmarunner', 'Karma Runner'],
  ['http', 'HTTP'],
  ['httprest', 'RESTful'],
  ['googleworkspace', 'Google Workspace'],
  ['oauth2', 'OAuth 2.0'],
  ['junit', 'JUnit'],
  ['jsonld', 'JSON LD'],
  ['blockcerts', 'Blockcerts'],
  ['gitlabcicd', 'GitLab CI/CD'],
  ['gitlabpages', 'GitLab Pages'],
  ['webcomponents', 'Web Components'],
  ['python-unittest', "Python's `unittest`"],
  ['pyqt', 'PyQt'],
  ['java', 'Java'],
  ['html', 'HTML'],
  ['css', 'CSS'],
]
