name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
  test:
    name: Test
    uses: ./.github/workflows/reusable-test.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  performance:
    name: Performance
    needs: build
    uses: ./.github/workflows/reusable-performance.yml
    permissions:
      checks: write
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
  deploy-gh-pages:
    name: Deploy to GitHub Pages (latest)
    if: github.event_name == 'push' && github.ref_name == 'refs/heads/main'
    needs: [build, lint, test, performance]
    uses: ./.github/workflows/reusable-deploy-github-pages.yml
    permissions:
      contents: read
      pages: write
      id-token: write
  deploy-cloudflare-pages:
    name: Deploy to Cloudflare Pages
    if: |
      (
        github.event_name == 'push' &&
        github.ref == 'refs/heads/main' &&
        fromJSON(vars.DEPLOY_TO_PRO_ON_MAIN)
      ) || (
        github.event_name == 'pull_request' &&
        !github.event.pull_request.head.repo.fork
      )
    needs: [build, lint, test, performance]
    uses: ./.github/workflows/reusable-deploy-cloudflare-pages.yml
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      contents: read
      deployments: write
  release:
    name: Release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build, lint, test, performance]
    uses: ./.github/workflows/reusable-release.yml
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
