name: Pull request

on:
  pull_request:

jobs:
  data:
    name: Data
    uses: ./.github/workflows/reusable-data.yml
  build:
    needs: data
    name: Build
    uses: ./.github/workflows/reusable-build.yml
  test:
    needs: data
    name: Test
    uses: ./.github/workflows/reusable-test.yml
    secrets:
      codecov-token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    name: Lint
    uses: ./.github/workflows/reusable-lint.yml
  style:
    name: Style
    uses: ./.github/workflows/reusable-style.yml
  performance:
    name: Performance
    needs: build
    uses: ./.github/workflows/reusable-performance.yml
    secrets:
      LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
      BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
  deploy-preview:
    name: Deploy preview
    needs: [build]
    uses: ./.github/workflows/reusable-deploy-cloudflare-pages.yml
    secrets:
      cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    permissions:
      contents: read
      deployments: write
