name: Pull request

on:
  pull_request:

jobs:
  build:
    name: Build
    uses: ./.github/workflows/reusable-build.yml
    permissions:
      contents: write
    with:
      artifact-name: build
      build-run-script: 'build:pullRequest'
  #test:
  #  name: Test
  #  uses: ./.github/workflows/reusable-test.yml
  #  secrets:
  #    codecov-token: ${{ secrets.CODECOV_TOKEN }}
  #lint:
  #  name: Lint
  #  uses: ./.github/workflows/reusable-lint.yml
  #style:
  #  name: Style
  #  uses: ./.github/workflows/reusable-style.yml
  #performance:
  #  name: Performance
  #  needs: build
  #  uses: ./.github/workflows/reusable-performance.yml
  #  with:
  #    build-artifact-name: build
  #  secrets:
  #    LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
  #    BUNDLEWATCH_GITHUB_TOKEN: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
  #deploy-preview:
  #  name: Deploy preview
  #  needs: [build]
  #  uses: ./.github/workflows/reusable-deploy-cloudflare-pages.yml
  #  with:
  #    build-artifact-name: build
  #  secrets:
  #    cloudflare-account-id: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
  #    cloudflare-api-token: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  #  permissions:
  #    contents: read
  #    deployments: write
