name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
      ref:
        description: Git reference to checkout. Defaults to @actions/checkout default.
        type: string
        required: false
        default: ''
      build-run-script:
        description: Build run script in package.json to execute
        type: string
        required: false
        default: build

# Needed for prebuild step: dry run a release.
# Git permissions are checked even in dry run mode 🙃
# https://github.com/semantic-release/semantic-release/blob/v21.1.1/index.js#L88
permissions:
  contents: write

jobs:
  build:
    name: Build and prerender app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ inputs.ref }}
          lfs: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Angular build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          key: ${{ env.cache-name }}-${{ inputs.ref != '' && inputs.ref || github.ref }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: Prebuild
        run: pnpm run prebuild
      - name: Build and prerender app (SSG)
        run: pnpm run ${{ inputs.build-run-script}}
      - name: Upload built app
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ inputs.artifact-name }}
          path: 'dist/@davidlj95/website/browser'
          retention-days: 5
