name: Test
on:
  workflow_call:
    inputs:
      ref:
        description: Git reference to checkout. Defaults to @actions/checkout default.
        type: string
        required: false
        default: ''
    secrets:
      codecov-token:
        description: Token to use to upload coverage to Codecov. Can be empty for forks https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/
        required: true

# Add those permissions if reporting test results
# https://github.com/dorny/test-reporter/issues/229
# permissions:
#   checks: write

env:
  COVERAGE_ARTIFACT_NAME_PREFIX: coverage-
  COVERAGE_DIR: coverage

jobs:
  templates-have-been-rendered:
    name: Templated files are rendered
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Render templates
        run: 'pnpm run prebuild:render-templates'
      - name: Ensure no pending changes
        run: cd .ci && make ensure-no-pending-changes

  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: cd .ci && make test
      - name: Report test results (as status check)
        uses: dorny/test-reporter@31a54ee7ebcacc03a09ea97a7e5465a47b84aea5 # v1
        if: (success() || failure()) && github.ref == 'refs/heads/main'
        with:
          name: Test results
          path: '*.xml'
          reporter: java-junit
      - name: Upload coverage results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}${{ github.job }}
          path: ${{ env.COVERAGE_DIR }}
          retention-days: 5

  component-test:
    name: Component tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.ref }}
        # 👇 Needed in order for the Cypress GitHub Action to work
        #    Action uses Cypress Module API to work & later report the result in check summary
        #    https://docs.cypress.io/guides/guides/module-api
        #    However, if not using a classic `node_modules` structure, Cypress can't find `@angular*` packages
        #    and fails. CLI works, but prefer to use the GitHub Action w/ Module API to get the results there
      - name: Configure pnpm to use hoisted node linker
        run: echo "node-linker=hoisted" >> .npmrc
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get Cypress cache info
        run: |
          echo "CYPRESS_PKG_JSON_VERSION=$(jq -r '.devDependencies.cypress' package.json)" >> $GITHUB_ENV
          # 👇 Cypress caching. Env var to specify dir + use default dir
          # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
          echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress" >> $GITHUB_ENV
      - name: Cypress cache
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        env:
          CACHE_NAME: cypress
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ env.CYPRESS_PKG_JSON_VERSION }}
        # 👇 Just in case first run fails and installed Cypress is not cached
        #    In that scenario, `cypress run` does not install it again and errors
      - name: Cypress install
        run: pnpm cypress install
      - name: Generate font subsets
        run: pnpm run prebuild:font-subsets
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # 👇 Action doesn't support pnpm caching right now
          # https://github.com/cypress-io/github-action/tree/v6.6.1?tab=readme-ov-file#pnpm
          # Given we're doing caching manually, installing apart to leverage cache
          install: false
          component: true
      - name: Upload coverage results
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}${{ github.job }}
          path: ${{ env.COVERAGE_DIR }}
          retention-days: 5

  coverage:
    name: Coverage
    needs: [unit-test, component-test]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download code coverage reports
        uses: actions/download-artifact@65a9edc5881444af0b9093a5e628f2fe47ea3b2e # v4
        with:
          pattern: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}*
          path: ${{ env.COVERAGE_DIR }}
          merge-multiple: true
      - name: Merge coverage reports
        run: pnpm run coverage:report:all
      - name: Upload to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          directory: ${{ env.COVERAGE_DIR }}
          token: ${{ secrets.codecov-token }}
