name: Test
on:
  workflow_call:
    secrets:
      codecov-token:
        description: Token to use to upload coverage to Codecov. Can be empty for forks https://about.codecov.io/blog/january-product-update-updating-the-codecov-ci-uploaders-to-the-codecov-cli/
        required: true

env:
  COVERAGE_ARTIFACT_NAME_PREFIX: coverage-
  COVERAGE_DIR: coverage

jobs:
  unit-test:
    name: Unit tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate data
        run: |
          pnpm run --filter scripts build
          pnpm run --filter scripts generate:font-subsets
          pnpm run --filter scripts generate:techs
          pnpm run --filter scripts generate:templated-files
          touch data/generated/release.json
      - name: Run tests
        run: cd .ci && make unit-test
      - name: Upload coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}${{ github.job }}
          path: ${{ env.COVERAGE_DIR }}
          retention-days: 5

  component-test:
    name: Component tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        # 👇 Needed in order for the Cypress GitHub Action to work
        #    Action uses Cypress Module API to work & later report the result in check summary
        #    https://docs.cypress.io/guides/guides/module-api
        #    However, if not using a classic `node_modules` structure, Cypress can't find `@angular*` packages
        #    and fails. CLI works, but prefer to use the GitHub Action w/ Module API to get the results there
      - name: Configure pnpm to use hoisted node linker
        run: echo "node-linker=hoisted" >> .npmrc
      - name: Setup
        uses: ./.github/actions/setup
      - name: Get Cypress cache info
        run: |
          echo "CYPRESS_PKG_JSON_VERSION=$(jq -r '.devDependencies.cypress' package.json)" >> "$GITHUB_ENV"
          # 👇 Cypress caching. Env var to specify dir + use default dir
          # https://docs.cypress.io/guides/continuous-integration/introduction#Caching
          echo "CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress" >> "$GITHUB_ENV"
      - name: Cypress cache
        uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf # v4
        env:
          CACHE_NAME: cypress
        with:
          path: ${{ env.CYPRESS_CACHE_FOLDER }}
          key: ${{ env.CACHE_NAME }}-${{ env.CYPRESS_PKG_JSON_VERSION }}
        # 👇 Just in case first run fails and installed Cypress is not cached
        #    In that scenario, `cypress run` does not install it again and errors
      - name: Cypress install
        run: pnpm cypress install
      - name: Generate data
        run: |
          pnpm run --filter scripts build
          pnpm run --filter scripts generate:font-subsets
          pnpm run --filter scripts generate:techs
          pnpm run --filter scripts generate:templated-files
          touch data/generated/release.json
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          # 👇 Action doesn't support pnpm caching right now
          # https://github.com/cypress-io/github-action/tree/v6.6.1?tab=readme-ov-file#pnpm
          # Given we're doing caching manually, installing apart to leverage cache
          install: false
          component: true
      - name: Upload coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}${{ github.job }}
          path: ${{ env.COVERAGE_DIR }}
          retention-days: 5

  coverage:
    name: Coverage
    needs: [unit-test, component-test]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download code coverage reports
        uses: actions/download-artifact@cc203385981b70ca67e1cc392babf9cc229d5806 # v4
        with:
          pattern: ${{ env.COVERAGE_ARTIFACT_NAME_PREFIX }}*
          path: ${{ env.COVERAGE_DIR }}
          merge-multiple: true
      - name: Merge coverage reports
        run: pnpm run coverage:report:all
      - name: Upload to Codecov
        uses: codecov/codecov-action@0565863a31f2c772f9f0395002a31e3f06189574 # v5.4.0
        with:
          directory: ${{ env.COVERAGE_DIR }}
          token: ${{ secrets.codecov-token }}
