name: Release
on:
  workflow_call:

# Required by
# https://github.com/semantic-release/github
# https://github.com/semantic-release/npm
permissions:
  contents: write # create release
  issues: write # comment on released issues
  pull-requests: write # comment on released PRs

# Run one after another
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-it:
    name: Release It!
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release

  semantic-release:
    if: false
    name: Semantic Release
    runs-on: ubuntu-latest
    # Adding some time in case many PRs have to be labeled, as it may time out otherwise
    # https://github.com/davidlj95/website/actions/runs/8238739780/job/22530445766
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm semantic-release
