name: Release
on:
  workflow_call:
    secrets:
      npm-token:
        required: true

# Required by
# https://github.com/semantic-release/github
# https://github.com/semantic-release/npm
permissions:
  # For GitHub release creation & issues / PR comments
  contents: write
  issues: write
  pull-requests: write
  # For NPM provenance
  id-token: write

# Run one after another
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  semantic-release:
    name: Semantic Release
    runs-on: ubuntu-latest
    # Adding some time in case many PRs have to be labeled, as it may time out otherwise
    # https://github.com/davidlj95/website/actions/runs/8238739780/job/22530445766
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      # Why this? https://github.com/npm/cli/issues/7279
      # Why this way? https://github.com/actions/setup-node/issues/213
      # Why only here? Because only the npm audit signatures command is affected
      - name: Install latest npm
        run: |
          npm install -g npm@latest &&
          npm --version &&
          npm list -g --depth 0
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.npm-token }}
        run: pnpm semantic-release
