name: Lint
on:
  workflow_call:
    inputs:
      ref:
        description: Git reference to checkout. Defaults to @actions/checkout default.
        type: string
        required: false
        default: ''

# Add those permissions if reporting test results
# https://github.com/dorny/test-reporter/issues/229
# permissions:
#   checks: write

jobs:
  code:
    name: Code
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run linter
        run: cd .ci && make lint
      - name: Report results (as status check)
        uses: dorny/test-reporter@v1
        if: (success() || failure()) && github.ref == 'refs/heads/main'
        with:
          name: Lint results
          path: '*.xml'
          reporter: java-junit

  commit-messages:
    name: Commit messages
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Lint last commit
        if: github.event_name == 'push'
        run: cd .ci && make lint-last-commit
      - name: Lint all PR commits
        if: github.event_name == 'pull_request'
        run: |
          pnpm commitlint \
            --from ${{ github.event.pull_request.base.sha }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
