name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          #👇 To generate release information
          fetch-depth: 0
          lfs: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate info for Angular cache key
        run: echo "week-of-year=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - name: Cache Angular build
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          # 👇 Update cache once a week. Best effort approach
          #    Otherwise it would never be invalidated
          key: ${{ env.cache-name }}-${{ env.week-of-year }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: Data tasks
        run: pnpm run data
      - name: Build app (with SSG)
        run: pnpm run ${{ github.event_name == 'pull_request' && 'build:pull-request' || 'build' }}
      - name: Upload built app
        uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4
        with:
          name: build
          path: 'dist/@davidlj95/website/browser'
          retention-days: 5
