name: Test
on:
  workflow_call:

# https://github.com/dorny/test-reporter/issues/229
permissions:
  checks: write

jobs:
  templates-have-been-rendered:
    name: Templated files are rendered
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Render templates
        run: cd .ci && make render-templates
      - name: Ensure no pending changes
        run: cd .ci && make ensure-no-pending-changes
  test:
    name: All tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: cd .ci && make test
      - name: Report coverage
        uses: livewing/lcov-job-summary@v1.1.0
        with:
          lcov: coverage/davidlj95/website/lcov.info
      - name: Report test results (as status check)
        uses: dorny/test-reporter@v1
        if: github.ref == 'refs/heads/main'
        with:
          name: Test results
          path: junit-test.xml
