name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
        default: ''

jobs:
  build:
    name: Build and prerender app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Angular build
        uses: actions/cache@v3
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          key: ${{ env.cache-name }}-${{ github.ref }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: Build and prerender app
        run: make -f .ci/Makefile build
      - name: Upload built app
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
          path: 'dist/@davidlj95/website'
          retention-days: 5
