name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
      ref:
        description: Git reference to checkout. Defaults to @actions/checkout default.
        type: string
        required: false
        default: ''
      target:
        description: Makefile target to run when building
        type: string
        required: false
        default: build

# Needed for prebuild step: dry run a release.
# Git permissions are checked even in dry run mode 🙃
# https://github.com/semantic-release/semantic-release/blob/v21.1.1/index.js#L88
permissions:
  contents: write

jobs:
  build:
    name: Build and prerender app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4
        with:
          ref: ${{ inputs.ref }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Angular build
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 # v3
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          key: ${{ env.cache-name }}-${{ inputs.ref != '' && inputs.ref || github.ref }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: Build and prerender app
        run: cd .ci && make ${{ inputs.target }}
      - name: Upload built app
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: ${{ inputs.artifact-name }}
          path: 'dist/@davidlj95/website/browser'
          retention-days: 5
