name: Lighthouse
on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string
    secrets:
      LHCI_GITHUB_APP_TOKEN:
        required: true

# Add those permissions if reporting test results
# https://github.com/dorny/test-reporter/issues/229
# permissions:
#   checks: write

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        # No setup step needed: latest stable Node.js & npm comes included with GitHub runners
        # https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md
      - name: Download built app
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build-artifact-name }}
      - name: Run Lighthouse CI
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
        run: cd .ci && make lighthouse
      - name: Report results (as status check)
        if: github.ref == 'refs/heads/main'
        uses: manrueda/lighthouse-report-action@v1.1.2
        with:
          reports: '.lighthouseci'
          github-token: ${{ secrets.GITHUB_TOKEN }}
