name: Lighthouse
on:
  workflow_call:
    inputs:
      build-artifact-name:
        required: true
        type: string

jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download built app
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build-artifact-name }}
      - name: Run Lighthouse CI
        run: |
          yarn dlx @lhci/cli@0.12.x autorun
      - name: Report results
        if: success() || failure()
        uses: manrueda/lighthouse-report-action@v1.0.1
        with:
          reports: '.lighthouseci'
          github-token: ${{ secrets.GITHUB_TOKEN }}
