name: Test
on:
  workflow_call:

# https://github.com/dorny/test-reporter/issues/229
permissions:
  checks: write

jobs:
  templates-have-been-rendered:
    name: Templated files are rendered
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Render templates
        run: cd .ci && make render-templates
      - name: Ensure no pending changes
        run: cd .ci && make ensure-no-pending-changes
  test:
    name: All tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: cd .ci && make test
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: test-results
          path: |
            coverage
            junit-test.xml
  report-coverage:
    needs: test
    name: Report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Download results
        uses: actions/download-artifact@v3
        with:
          name: test-results
      - name: Report coverage
        uses: livewing/lcov-job-summary@v1.1.0
        with:
          lcov: coverage/davidlj95/website/lcov.info
  report-results:
    needs: test
    name: Report test results (as status check)
    uses: ./.github/workflows/reusable-test-reporter.yml
    if: github.ref == 'refs/heads/main'
    permissions:
      checks: write
    with:
      artifact-name: test-results
      name: Test results
      path: junit-test.xml
