name: Test
on:
  workflow_call:

jobs:
  test:
    name: All tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run tests
        run: make -f .ci/Makefile test
      - name: Report tests
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Karma tests
          path: 'junit-tests.xml'
          reporter: jest-junit
