name: Release
on:
  workflow_call:

permissions:
  contents: write # create release
  issues: write # comment on released issues
  pull-requests: write # comment on released PRs

# Run one after another
concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release-it:
    name: Release It!
    runs-on: ubuntu-latest
    # Adding more time in case it needs to comment on several GitHub issues / PRs
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup
        uses: ./.github/actions/setup
      - name: Download built app
        uses: actions/download-artifact@634f93cb2916e3fdff6788551b99b062d0335ce0 # v5
        with:
          name: build
          path: dist/@davidlj95/website/browser
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: pnpm run release
