name: Lint
on:
  workflow_call:

# https://github.com/dorny/test-reporter/issues/229
permissions:
  checks: write

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Run linter
        run: cd .ci && make lint
      - name: Upload results
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: lint-results
          path: 'junit-lint.xml'
  report:
    needs: lint
    name: Report lint results (as status check)
    uses: ./.github/workflows/reusable-test-reporter.yml
    if: github.ref == 'refs/heads/main'
    permissions:
      checks: write
    with:
      artifact-name: lint-results
      name: Lint results
      path: junit-lint.xml
