name: Build
on:
  workflow_call:
    inputs:
      artifact-name:
        required: false
        type: string
      ref:
        description: Git reference to checkout. Defaults to @actions/checkout default.
        type: string
        required: false
        default: ''
      target:
        description: Makefile target to run when building
        type: string
        required: false
        default: build

# Needed for prebuild step: dry run a release.
# Git permissions are checked even in dry run mode 🙃
# https://github.com/semantic-release/semantic-release/blob/v21.1.1/index.js#L88
permissions:
  contents: write

jobs:
  build:
    name: Build and prerender app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          ref: ${{ inputs.ref }}
          lfs: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Cache Angular build
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          key: ${{ env.cache-name }}-${{ inputs.ref != '' && inputs.ref || github.ref }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: Build and prerender app
        run: cd .ci && make ${{ inputs.target }}
      - name: Upload built app
        if: ${{ inputs.artifact-name != '' }}
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3 # v4
        with:
          name: ${{ inputs.artifact-name }}
          path: 'dist/@davidlj95/website/browser'
          retention-days: 5
