name: Build
on:
  workflow_call:

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4
        with:
          #👇 To generate release information
          fetch-depth: 0
          lfs: true
      - name: Setup
        uses: ./.github/actions/setup
      - name: Generate info for Angular cache key
        run: echo "week-of-year=$(date --utc '+%V')" >> "$GITHUB_ENV"
      - name: Cache Angular build
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        env:
          cache-name: angular-cache
        with:
          path: .angular/cache
          # 👇 Update cache once a week. Best effort approach
          #    Otherwise it would never be invalidated
          key: ${{ env.cache-name }}-${{ env.week-of-year }}
          restore-keys: |
            ${{ env.cache-name }}
      - name: App data
        run: pnpm run app-data
      - name: Build app (with SSG)
        run: pnpm run ${{ github.event_name == 'pull_request' && 'build:pull-request' || 'build' }}
      - name: Resume PDF
        run: pnpm run --filter scripts resume-pdf
      - name: Upload built app
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: build
          path: 'dist/@davidlj95/website/browser'
          retention-days: 5
